const users = {
  volunteer:{email:"alia@eurasia.org",password:"demo2026",role:"volunteer",name:"Алия Ибрагимова",short:"Алия",initials:"АИ",label:"Участник",start:"home"},
  organization:{email:"organizer@eurasia.org",password:"org2026",role:"organization",name:"Фонд «Чистый город»",short:"Чистый город",initials:"ЧГ",label:"Организация",start:"organization"},
  partner:{email:"partner@eurasia.org",password:"partner2026",role:"partner",name:"Сеть кофеен «Соседи»",short:"Соседи",initials:"СБ",label:"Партнер",start:"partner"},
  admin:{email:"admin@eurasia.org",password:"admin2026",role:"admin",name:"Администратор платформы",short:"Администратор",initials:"AD",label:"Администратор",start:"admin"}
};
const access = {
  volunteer:["home","events","missions","rewards","profile","wallet","social"],
  organization:["organization","events","profile"],
  partner:["partner","events","rewards","profile"],
  admin:["admin","events","rewards","profile"]
};
const state = { currentUser:null, nextRequestId:20 };
const notifications = {
  volunteer:[
    {id:1,icon:"✓",title:"Участие подтверждено",text:"Начислено 150 E за фестиваль культур Евразии.",time:"Сегодня, 09:42",page:"wallet",read:false,tone:"green"},
    {id:2,icon:"◇",title:"Событие уже скоро",text:"«Чистые берега Большой Алматинки» начнется 15 июня в 09:00.",time:"Сегодня, 08:15",page:"events",read:false,tone:"purple"},
    {id:3,icon:"✦",title:"Новая награда партнера",text:"В каталоге появился курс по проектному менеджменту.",time:"Вчера, 18:30",page:"rewards",read:false,tone:"yellow"},
    {id:4,icon:"+",title:"Марат добавил вас в друзья",text:"Теперь вы можете общаться в личном чате.",time:"10 июня, 14:22",page:"social",read:true,tone:"purple"}
  ],
  organization:[
    {id:11,icon:"◎",title:"Новый QR check-in",text:"Марат Касымов ожидает подтверждения участия.",time:"Сегодня, 09:12",page:"organization",read:false,tone:"green"},
    {id:12,icon:"◇",title:"Мероприятие на модерации",text:"«Городской сад: новый сезон» отправлено администратору.",time:"Вчера, 16:40",page:"organization",read:false,tone:"yellow"},
    {id:13,icon:"✓",title:"Статистика обновлена",text:"За неделю подтверждено 24 новых участия.",time:"10 июня, 12:10",page:"organization",read:true,tone:"purple"}
  ],
  partner:[
    {id:21,icon:"✦",title:"Награда ожидает выдачи",text:"Марат Касымов показал промокод EUR-4812.",time:"Сегодня, 10:08",page:"partner",read:false,tone:"yellow"},
    {id:22,icon:"✓",title:"Предложение активно",text:"«Завтрак волонтера» прошло модерацию.",time:"Вчера, 17:25",page:"partner",read:false,tone:"green"},
    {id:23,icon:"↗",title:"Конверсия выросла",text:"Получение наград выросло на 18% за месяц.",time:"9 июня, 11:15",page:"partner",read:true,tone:"purple"}
  ],
  admin:[
    {id:31,icon:"!",title:"Новая заявка на модерацию",text:"Мероприятию «Городской марафон добра» нужно назначить награду.",time:"Сегодня, 10:02",page:"admin",read:false,tone:"red"},
    {id:32,icon:"⚙",title:"Требуется решение",text:"Крупная награда на 1 200 E ожидает проверки.",time:"Сегодня, 09:48",page:"admin",read:false,tone:"yellow"},
    {id:33,icon:"!",title:"Новая жалоба",text:"Поступила жалоба на некорректные сообщения.",time:"Вчера, 20:11",page:"admin",read:false,tone:"red"},
    {id:34,icon:"✓",title:"Антифрод-проверка завершена",text:"98,7% операций прошли автоматическую проверку.",time:"Вчера, 08:00",page:"admin",read:true,tone:"green"}
  ]
};
const profiles = {
  volunteer:{name:"Алия Ибрагимова",city:"Алматы",interests:"Экология, образование, культура",email:"alia@eurasia.org",phone:"+7 700 111 22 33",social:"https://instagram.com/aliya_good",initials:"АИ",type:"Социальный профиль участника",showContacts:true,showSocial:true},
  organization:{name:"Фонд «Чистый город»",city:"Алматы",interests:"Экология, городские инициативы",email:"contact@clean-city.org",phone:"+7 727 000 00 00",social:"https://instagram.com/clean_city",initials:"ЧГ",type:"Профиль организации",showContacts:true,showSocial:true},
  partner:{name:"Сеть кофеен «Соседи»",city:"Алматы и Астана",interests:"Награды, социальные проекты",email:"partner@eurasia.org",phone:"+7 700 555 44 33",social:"https://instagram.com/sosedi_coffee",initials:"СБ",type:"Профиль партнера",showContacts:true,showSocial:true},
  admin:{name:"Администратор платформы",city:"Центральный офис",interests:"Модерация и безопасность",email:"admin@eurasia.org",phone:"+7 700 000 00 01",social:"",initials:"AD",type:"Служебный профиль",showContacts:false,showSocial:false}
};
const volunteerData = {
  balance:1240, joined:new Set([1]), checkedIn:new Set(), missionStatus:new Map(), redeemed:new Set(), friends:new Set([1]), profileSocialAdded:false,
  transactions:[
    {title:"Фестиваль культур Евразии",rule:"Участие подтверждено организацией",amount:150,status:"Начислено",date:"7 июня, 18:42"},
    {title:"Кофе для тебя и друга",rule:"Покупка награды · PROMO-4821",amount:-180,status:"Списано",date:"5 июня, 12:10"},
    {title:"Профиль заполнен на 80%",rule:"Одноразовый бонус профиля",amount:20,status:"Начислено",date:"1 июня, 14:08"}
  ]
};
const organizationData = {
  verified:true,
  events:[
    {id:1,title:"Чистые берега Большой Алматинки",status:"Опубликовано",reward:180,participants:[{name:"Алия Ибрагимова",initials:"АИ",status:"Зарегистрирован",time:"—"},{name:"Марат Касымов",initials:"МК",status:"QR check-in",time:"09:12"},{name:"София Алимова",initials:"СА",status:"Подтверждено",time:"09:16"}]},
    {id:5,title:"Городской сад: новый сезон",status:"На модерации",reward:null,participants:[]},
    {id:8,title:"Эколекция для школьников",status:"Черновик",reward:null,participants:[]}
  ]
};
const partnerData = {
  rewards:[
    {id:3,title:"Кофе для тебя и друга",price:180,quantity:42,status:"Активна",issued:128},
    {id:9,title:"Завтрак волонтера",price:260,quantity:20,status:"Активна",issued:34},
    {id:10,title:"Скидка 30% на напитки",price:100,quantity:100,status:"На модерации",issued:0}
  ],
  redemptions:[{id:1,user:"Марат Касымов",initials:"МК",reward:"Кофе для тебя и друга",code:"EUR-4812",status:"Ожидает выдачи"},{id:2,user:"Алия Ибрагимова",initials:"АИ",reward:"Кофе для тебя и друга",code:"EUR-4821",status:"Ожидает выдачи"}]
};
const adminData = {
  requests:[
    {id:1,type:"organization",label:"Организация",title:"Фонд «Открытые сердца»",author:"Фонд «Открытые сердца»",detail:"Проверка регистрационных данных",status:"Ожидает"},
    {id:2,type:"event",label:"Мероприятие",title:"Городской марафон добра",author:"Qazaq Volunteers",detail:"Нужно назначить награду",amount:200,status:"Ожидает"},
    {id:3,type:"large_reward",label:"Крупная награда",title:"Поездка в волонтерский лагерь",author:"Алия Ибрагимова",detail:"Резерв 1 200 E",amount:1200,status:"Ожидает"},
    {id:4,type:"complaint",label:"Жалоба",title:"Некорректные сообщения",author:"София Алимова",detail:"Жалоба на пользователя user-482",status:"Ожидает"}
  ],
  audit:[{action:"Назначена награда 180 E",object:"Чистые берега Большой Алматинки",actor:"Администратор",date:"Сегодня, 09:20"},{action:"Организация верифицирована",object:"Фонд «Чистый город»",actor:"Администратор",date:"9 июня, 16:10"}]
};

const events=[
  {id:1,day:"15",month:"ИЮНЯ",tag:"ЭКОЛОГИЯ",title:"Чистые берега Большой Алматинки",text:"Вернем любимому месту его естественную красоту.",reward:180,tone:""},
  {id:2,day:"18",month:"ИЮНЯ",tag:"ОБРАЗОВАНИЕ",title:"Разговорный клуб для школьников",text:"Практика языков и новые знакомства.",reward:120,tone:"yellow"},
  {id:3,day:"22",month:"ИЮНЯ",tag:"КУЛЬТУРА",title:"Фестиваль культур Евразии",text:"Помоги гостям открыть традиции народов.",reward:200,tone:"red"},
  {id:4,day:"27",month:"ИЮНЯ",tag:"ПОМОЩЬ",title:"Теплый день в центре поддержки",text:"Мастер-классы для старшего поколения.",reward:160,tone:"yellow"},
  {id:5,day:"02",month:"ИЮЛЯ",tag:"ЭКОЛОГИЯ",title:"Городской сад: новый сезон",text:"Создадим зеленое место встречи.",reward:150,tone:"red"},
  {id:6,day:"06",month:"ИЮЛЯ",tag:"КОМАНДА",title:"Школа лидеров волонтерства",text:"День практики, идей и знакомств.",reward:220,tone:""}
];
const missions=[
  {id:1,icon:"♻",title:"Один день без пластика",text:"Загрузи фото результата",reward:30,method:"Скриншот + модерация"},
  {id:2,icon:"↗",title:"Расскажи о добром деле",text:"Опубликуй историю с #ЕвразияВместе",reward:20,method:"Ссылка / UTM"},
  {id:3,icon:"◎",title:"Пройди мини-курс по первой помощи",text:"Посмотри урок и ответь на вопросы",reward:60,method:"Автопроверка"},
  {id:4,icon:"⌖",title:"Найди пункт переработки рядом",text:"Отметь точку на карте",reward:25,method:"Геолокация"}
];
const rewards=[
  {id:1,icon:"🎟",title:"Билет на фестиваль Евразия",text:"Закрытая программа и встречи с лидерами.",price:800,tone:"red",approval:true},
  {id:2,icon:"📚",title:"Курс по проектному менеджменту",text:"Месяц обучения и сертификат.",price:650,tone:"",approval:false},
  {id:3,icon:"☕",title:"Кофе для тебя и друга",text:"Два напитка в кофейнях партнера.",price:180,tone:"yellow",approval:false},
  {id:4,icon:"●",title:"Фирменный набор волонтера",text:"Кепка, шоппер и значки.",price:500,tone:"",approval:false},
  {id:5,icon:"▲",title:"Поездка в волонтерский лагерь",text:"Три дня в горах вместе с командой.",price:1200,tone:"yellow",approval:true},
  {id:6,icon:"▶",title:"Два билета в кино",text:"Любой сеанс в сети партнера.",price:350,tone:"red",approval:false}
];
const rules=[{title:"Подтвержденное участие",amount:"100–250 E",detail:"Размер назначает администратор до публикации"},{title:"Фото профиля",amount:"+10 E",detail:"Один раз после технической проверки"},{title:"Социальная ссылка",amount:"+5 E",detail:"Лимит 3, без повторных начислений"},{title:"Полный профиль",amount:"+20 E",detail:"Бонус при заполнении от 80%"}];
const people=[{id:1,initials:"МК",name:"Марат Касымов",city:"Алматы",interests:"Экология, спорт",email:"marat@example.org",social:"https://instagram.com/marat_volunteer",hours:62,events:18,detail:"Алматы · экология · 24 общих друга",showContacts:true,showSocial:true},{id:2,initials:"СА",name:"София Алимова",city:"Астана",interests:"Образование, помощь детям",email:"sofia@example.org",social:"https://t.me/sofia_volunteer",hours:41,events:11,detail:"Астана · образование · 8 общих друзей",showContacts:false,showSocial:true},{id:3,initials:"ДА",name:"Данияр Ахметов",city:"Шымкент",interests:"Культура, городские события",email:"daniyar@example.org",social:"",hours:29,events:7,detail:"Шымкент · культура · 5 общих друзей",showContacts:false,showSocial:false}];

const fmt=n=>n.toLocaleString("ru-RU");
const roleIs=(...roles)=>state.currentUser&&roles.includes(state.currentUser.role);
function requireRole(...roles){if(roleIs(...roles))return true;toast("Действие недоступно для вашей роли");return false}
function audit(action,object){adminData.audit.unshift({action,object,actor:state.currentUser?.name||"Система",date:"Только что"})}
function request(data){adminData.requests.unshift({id:state.nextRequestId++,status:"Ожидает",...data});addNotification("admin",`Новая заявка: ${data.label}`,`${data.title} · ${data.detail}`,"admin","!",data.type==="complaint"?"red":"yellow");renderAdmin()}
function addNotification(role,title,text,page,icon="✓",tone="green"){notifications[role].unshift({id:Date.now(),title,text,page,icon,tone,time:"Только что",read:false});if(state.currentUser?.role===role)renderNotifications()}
function addTransaction(title,rule,amount,status="Начислено"){if(status!=="Ожидает"&&status!=="Зарезервировано")volunteerData.balance+=amount;if(status==="Зарезервировано")volunteerData.balance+=amount;volunteerData.transactions.unshift({title,rule,amount,status,date:"Только что"});updateBalance();renderTransactions()}
function updateBalance(){["balance","balance-rewards","balance-profile","balance-wallet"].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=fmt(volunteerData.balance)})}
function renderEvents(){const volunteer=roleIs("volunteer");document.getElementById("events-grid").innerHTML=events.map(e=>`<article class="event-card"><div class="card-art ${e.tone}"><span class="tag light">${e.tag}</span><small>${e.month}</small><b>${e.day}</b></div><div class="card-body"><h3>${e.title}</h3><p>${e.text}</p><div class="card-footer"><strong>+${e.reward} E</strong>${volunteer?`<button class="primary ${volunteerData.joined.has(e.id)?"joined":""}" data-join="${e.id}">${volunteerData.joined.has(e.id)?"Вы записаны":"Записаться"}</button>`:`<button class="primary secondary-action" data-view-event="${e.id}">Открыть карточку</button>`}</div></div></article>`).join("")}
function renderMissions(){document.getElementById("home-missions").innerHTML=missions.slice(0,3).map(m=>`<div class="mini-mission"><span class="mission-icon">${m.icon}</span><div><b>${m.title}</b><small>${m.method}</small></div><span class="reward-label">+${m.reward} E</span></div>`).join("");document.getElementById("missions-list").innerHTML=missions.map(m=>{const s=volunteerData.missionStatus.get(m.id)||"Доступно";return`<article class="mission-row"><span class="mission-icon">${m.icon}</span><div><h3>${m.title}</h3><p>${m.text} · ${m.method}</p></div><span class="reward-label">+${m.reward} E</span><button class="primary ${s==="Выполнено"?"joined":s==="Ожидает проверки"?"pending-button":""}" data-mission="${m.id}">${s==="Доступно"?"Отправить":s}</button></article>`}).join("")}
function renderRewards(){const volunteer=roleIs("volunteer");document.getElementById("rewards-grid").innerHTML=rewards.map(r=>`<article class="reward-card"><div class="card-art ${r.tone}">${r.icon}</div><div class="card-body"><span class="eyebrow">${r.approval?"ТРЕБУЕТ ПОДТВЕРЖДЕНИЯ":"НАГРАДА ПАРТНЕРА"}</span><h3>${r.title}</h3><p>${r.text}</p><div class="card-footer"><strong>${fmt(r.price)} E</strong>${volunteer?`<button class="primary ${volunteerData.redeemed.has(r.id)?"joined":""}" data-reward="${r.id}">${volunteerData.redeemed.has(r.id)?"Заявка создана":"Получить"}</button>`:`<button class="primary secondary-action" data-view-reward="${r.id}">Посмотреть</button>`}</div></div></article>`).join("")}
function renderTransactions(){const el=document.getElementById("transactions");if(!el)return;el.innerHTML=volunteerData.transactions.map(t=>`<div class="transaction"><span class="transaction-icon">${t.amount>0?"+":"−"}</span><div><b>${t.title}</b><small>${t.rule} · ${t.date}</small></div><span class="status-badge ${t.status==="Ожидает"||t.status==="Зарезервировано"?"review":"approved"}">${t.status}</span><strong class="${t.amount>0?"positive":"negative"}">${t.amount>0?"+":""}${t.amount} E</strong></div>`).join("");document.getElementById("user-rules").innerHTML=rules.map(r=>`<div class="rule-row"><div><b>${r.title}</b><small>${r.detail}</small></div><strong>${r.amount}</strong></div>`).join("")}
function renderPeople(){document.getElementById("people-list").innerHTML=people.map(p=>`<div class="person-row"><button class="person-avatar avatar-button" data-view-person="${p.id}">${p.initials}</button><button class="person-main" data-view-person="${p.id}"><b>${p.name}</b><small>${p.detail}</small></button><button class="mini-btn ${volunteerData.friends.has(p.id)?"approve":""}" data-friend="${p.id}">${volunteerData.friends.has(p.id)?"В друзьях":"+ Добавить"}</button></div>`).join("")}
function renderOrganization(){document.getElementById("org-events").innerHTML=organizationData.events.map(e=>`<div class="moderation-row"><span class="transaction-icon">${e.status==="Опубликовано"?"✓":"◷"}</span><div><b>${e.title}</b><small>${e.status}${e.reward?` · назначено ${e.reward} E`:" · награда назначается администратором"}</small></div><span class="status-badge ${e.status==="Опубликовано"?"approved":"review"}">${e.status}</span>${e.status==="Черновик"?`<button class="mini-btn approve" data-send-event="${e.id}">На модерацию</button>`:""}</div>`).join("");const event=organizationData.events[0];document.getElementById("participants").innerHTML=event.participants.map((p,i)=>`<div class="participant-row"><span class="participant-avatar">${p.initials}</span><div><b>${p.name}</b><small>${p.status} · ${p.time}</small></div>${p.status==="QR check-in"?`<button class="mini-btn approve" data-confirm-person="${i}">Подтвердить</button>`:`<span class="status-badge ${p.status==="Подтверждено"?"approved":""}">${p.status}</span>`}</div>`).join("")}
function renderPartner(){document.getElementById("partner-rewards").innerHTML=partnerData.rewards.map(r=>`<div class="moderation-row"><span class="transaction-icon">✦</span><div><b>${r.title}</b><small>${r.price} E · остаток ${r.quantity} · выдано ${r.issued}</small></div><span class="status-badge ${r.status==="Активна"?"approved":"review"}">${r.status}</span><button class="mini-btn" data-edit-partner-reward="${r.id}">Изменить</button></div>`).join("");document.getElementById("partner-redemptions").innerHTML=partnerData.redemptions.map(r=>`<div class="participant-row"><span class="participant-avatar">${r.initials}</span><div><b>${r.user}</b><small>${r.reward} · ${r.code}</small></div><button class="mini-btn approve" data-issue="${r.id}">Подтвердить выдачу</button></div>`).join("");document.getElementById("partner-pending").textContent=partnerData.redemptions.length}
function renderAdmin(tab="moderation"){const el=document.getElementById("admin-content");if(!el)return;document.getElementById("moderation-count").textContent=adminData.requests.length;if(tab==="moderation")el.innerHTML=`<div class="data-panel"><div class="panel-head"><div><span class="eyebrow">Конкретные заявки</span><h3>Очередь модерации</h3></div><span class="status-badge review">SLA: 4 часа</span></div><div class="moderation-list">${adminData.requests.map(r=>`<div class="moderation-row"><span class="transaction-icon">!</span><div><b>${r.label}: ${r.title}</b><small>Автор: ${r.author} · ${r.detail}</small></div>${r.type==="event"?`<input class="reward-input" data-reward-input="${r.id}" type="number" value="${r.amount||150}" min="0" max="500">`:""}<div class="moderation-actions"><button class="mini-btn approve" data-moderate="${r.id}" data-decision="approve">Одобрить</button><button class="mini-btn reject" data-moderate="${r.id}" data-decision="reject">Отклонить</button></div></div>`).join("")||"<p>Очередь пуста</p>"}</div></div>`;
  if(tab==="rules")el.innerHTML=`<div class="dashboard-grid"><div class="data-panel"><div class="panel-head"><div><span class="eyebrow">Настраиваемые рамки</span><h3>Правила начисления</h3></div></div><div class="rule-list">${rules.map(r=>`<div class="rule-row"><span class="status-badge approved">Активно</span><div><b>${r.title}</b><small>${r.detail}</small></div><strong>${r.amount}</strong></div>`).join("")}</div></div><div class="data-panel"><div class="panel-head"><h3>Антифрод</h3></div><div class="rule-list"><div class="rule-row"><div><b>Одна награда за участие</b><small>Повторный check-in блокируется</small></div><span class="status-badge approved">Вкл</span></div><div class="rule-row"><div><b>Ручная проверка от 500 E</b><small>Крупные начисления и награды</small></div><span class="status-badge approved">Вкл</span></div></div></div></div>`;
  if(tab==="users")el.innerHTML=`<div class="dashboard-grid"><div class="data-panel"><div class="panel-head"><h3>Пользователи</h3></div><div class="rule-list">${["Алия Ибрагимова · участник","Фонд «Чистый город» · организация","Сеть кофеен «Соседи» · партнер"].map((x,i)=>`<div class="rule-row"><div><b>${x}</b><small>Активен · нарушений: ${i}</small></div><button class="mini-btn reject" data-block-user="${i}">Ограничить</button></div>`).join("")}</div></div><div class="data-panel"><div class="panel-head"><h3>Жалобы</h3></div><div class="rule-list"><div class="rule-row"><div><b>Некорректные сообщения</b><small>Жалоба Софии на user-482</small></div><button class="mini-btn approve" data-resolve-complaint>Рассмотреть</button></div></div></div></div>`;
  if(tab==="audit")el.innerHTML=`<div class="data-panel"><div class="panel-head"><div><span class="eyebrow">Неизменяемая история</span><h3>Журнал административных решений</h3></div></div><div class="transaction-list">${adminData.audit.map(a=>`<div class="transaction"><span class="transaction-icon">⚙</span><div><b>${a.action}</b><small>${a.object} · ${a.actor} · ${a.date}</small></div></div>`).join("")}</div></div>`;
  if(tab==="analytics")el.innerHTML=`<div class="analytics-grid"><div class="data-panel"><div class="panel-head"><h3>Движение токенов</h3><b class="positive">+12.4%</b></div><div class="chart"><span style="height:42%" data-label="Пн"></span><span style="height:65%" data-label="Вт"></span><span style="height:53%" data-label="Ср"></span><span style="height:82%" data-label="Чт"></span><span style="height:70%" data-label="Пт"></span><span style="height:95%" data-label="Сб"></span><span style="height:76%" data-label="Вс"></span></div></div><div class="data-panel"><div class="panel-head"><h3>Показатели</h3></div><div class="rule-list"><div class="rule-row"><div><b>Запись → участие</b></div><strong>76%</strong></div><div class="rule-row"><div><b>Средняя награда</b></div><strong>142 E</strong></div><div class="rule-row"><div><b>Потрачено токенов</b></div><strong>38%</strong></div></div></div></div>`}
function switchAuth(view){document.querySelectorAll("[data-auth-tab]").forEach(tab=>tab.classList.toggle("active",tab.dataset.authTab===view));document.querySelectorAll("[data-auth-view]").forEach(panel=>panel.classList.toggle("active",panel.dataset.authView===view));document.querySelector(".auth-tabs").dataset.active=view;document.getElementById("login-error").textContent=""}
function applyRole(user){state.currentUser=user;document.body.dataset.role=user.role;document.querySelectorAll("[data-roles]").forEach(el=>el.classList.toggle("role-hidden",!el.dataset.roles.split(",").includes(user.role)));document.getElementById("side-user-name").textContent=user.short;document.getElementById("side-user-role").textContent=user.label;document.getElementById("header-role").textContent=user.label;renderProfile();renderEvents();renderRewards();renderNotifications();go(user.start);const screen=document.getElementById("login-screen");screen.classList.add("leaving");setTimeout(()=>{screen.classList.add("hidden");screen.classList.remove("leaving","entering");toast(`Вход выполнен: ${user.label}`)},window.matchMedia("(prefers-reduced-motion: reduce)").matches?0:560)}
function logout(){closeNotifications();state.currentUser=null;delete document.body.dataset.role;document.getElementById("login-form").reset();const register=document.getElementById("register-form");register.reset();register.classList.remove("register-success");register.querySelector(".auth-submit span").textContent="Создать профиль";register.querySelector(".auth-submit b").textContent="→";register.querySelector(".auth-submit").disabled=false;document.querySelectorAll(".demo-account.selected").forEach(x=>x.classList.remove("selected"));switchAuth("login");const screen=document.getElementById("login-screen");screen.classList.remove("hidden","leaving");screen.classList.add("entering");setTimeout(()=>screen.classList.remove("entering"),650)}
function go(page){if(!state.currentUser)return;if(!access[state.currentUser.role].includes(page)){toast("Недостаточно прав для этого раздела");page=state.currentUser.start}document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===page));document.querySelectorAll("[data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===page));const titles={home:`Добрый день, ${state.currentUser.short}!`,events:"Каталог мероприятий",missions:"Миссии",rewards:"Каталог наград",profile:"Профиль",wallet:"Кошелек",social:"Друзья и чат",organization:"Кабинет организации",partner:"Кабинет партнера",admin:"Административная панель"};document.getElementById("page-title").textContent=titles[page];window.scrollTo({top:0,behavior:"smooth"})}
function toast(text){const el=document.getElementById("toast");el.textContent=text;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
function modal(title,text,icon="✓"){document.getElementById("modal-title").textContent=title;document.getElementById("modal-text").innerHTML=text;document.getElementById("modal-icon").textContent=icon;document.getElementById("modal").classList.add("show")}
function renderNotifications(){if(!state.currentUser)return;const list=notifications[state.currentUser.role],unread=list.filter(n=>!n.read).length,count=document.getElementById("notification-count");count.textContent=unread;count.classList.toggle("hidden-count",!unread);document.getElementById("notification-summary").textContent=unread?`${unread} непрочитанных`:"Все уведомления прочитаны";document.getElementById("notification-list").innerHTML=list.map(n=>`<button class="notification-item ${n.read?"":"unread"}" data-notification="${n.id}"><span class="notification-icon ${n.tone}">${n.icon}</span><span class="notification-copy"><b>${n.title}</b><small>${n.text}</small><time>${n.time}</time></span>${n.read?"":'<i aria-label="Новое"></i>'}</button>`).join("")||'<div class="notification-empty"><b>Пока уведомлений нет</b><span>Здесь появятся важные события платформы.</span></div>'}
function openNotifications(){renderNotifications();document.getElementById("notification-panel").classList.add("show");document.getElementById("notification-overlay").classList.add("show");document.getElementById("notification-panel").setAttribute("aria-hidden","false");document.getElementById("notification-button").setAttribute("aria-expanded","true")}
function closeNotifications(){document.getElementById("notification-panel").classList.remove("show");document.getElementById("notification-overlay").classList.remove("show");document.getElementById("notification-panel").setAttribute("aria-hidden","true");document.getElementById("notification-button").setAttribute("aria-expanded","false")}
function openCalculator(){modal("Калькулятор токенов",`<div class="token-calculator"><label>Целевая награда<select id="calc-goal"><option value="2500">Большая волонтерская поездка — 2 500 E</option>${rewards.map(r=>`<option value="${r.price}">${r.title} — ${r.price} E</option>`).join("")}</select></label><label>Планируемые мероприятия<input id="calc-events" value="2" type="number" min="0" max="20"></label><label>Планируемые миссии<input id="calc-missions" value="3" type="number" min="0" max="30"></label><label><input id="calc-profile" type="checkbox"> Завершить профиль (+25 E)</label><div class="calculation"><span>Подтвержденный баланс</span><strong id="calc-current"></strong></div><div class="calculation"><span>Прогнозируемое начисление</span><strong id="calc-forecast"></strong></div><div class="calculation"><span>Останется накопить</span><strong id="calc-left"></strong></div></div>`,"E");const calc=()=>{const goal=+document.getElementById("calc-goal").value,forecast=+document.getElementById("calc-events").value*180 + +document.getElementById("calc-missions").value*35 +(document.getElementById("calc-profile").checked?25:0);document.getElementById("calc-current").textContent=`${fmt(volunteerData.balance)} E`;document.getElementById("calc-forecast").textContent=`+${fmt(forecast)} E`;document.getElementById("calc-left").textContent=`${fmt(Math.max(0,goal-volunteerData.balance-forecast))} E`};["calc-goal","calc-events","calc-missions","calc-profile"].forEach(id=>document.getElementById(id).addEventListener("input",calc));calc()}
function openEventForm(){modal("Создать мероприятие",`<div class="token-calculator"><label>Название<input id="new-event-title" value="Новое волонтерское мероприятие"></label><label>Описание<input id="new-event-description" value="Полезное событие для города"></label><label>Дата<input id="new-event-date" type="date" value="2026-07-12"></label><div class="calculation"><span>Награда</span><strong>Назначит администратор</strong></div><button class="primary wide" data-submit-event>Создать черновик</button></div>`,"◇")}
function openPartnerRewardForm(existing){modal(existing?"Изменить награду":"Создать награду",`<div class="token-calculator"><label>Название<input id="partner-reward-title" value="${existing?.title||"Новое предложение партнера"}"></label><label>Стоимость в токенах<input id="partner-reward-price" type="number" min="1" value="${existing?.price||250}"></label><label>Количество<input id="partner-reward-quantity" type="number" min="1" value="${existing?.quantity||50}"></label><button class="primary wide" data-save-partner-reward="${existing?.id||""}">${existing?"Сохранить и отправить на модерацию":"Создать и отправить на модерацию"}</button></div>`,"✦")}
function openRuleForm(){modal("Новое правило токенов",`<div class="token-calculator"><label>Действие<input id="new-rule-title" value="Новое полезное действие"></label><label>Количество токенов<input id="new-rule-amount" type="number" min="1" max="500" value="20"></label><label>Условия и лимит<input id="new-rule-detail" value="Один раз после ручной проверки"></label><button class="primary wide" data-submit-rule>Добавить правило</button></div>`,"⚙")}
function setAvatar(el,p){el.textContent=p.avatar?"":p.initials;el.style.backgroundImage=p.avatar?`url(${p.avatar})`:""}
function socialLabel(url){if(!url)return"Не указана";try{const u=new URL(url);return `${u.hostname.replace("www.","")} / ${u.pathname.replaceAll("/","")||"профиль"}`}catch{return url}}
function renderProfile(){if(!state.currentUser)return;const p=profiles[state.currentUser.role];setAvatar(document.getElementById("profile-photo"),p);document.getElementById("profile-display-name").textContent=p.name;document.getElementById("profile-display-meta").textContent=`${p.city} · ${p.interests}`;document.getElementById("profile-type").textContent=p.type;document.getElementById("profile-detail-city").textContent=p.city||"Не указан";document.getElementById("profile-detail-interests").textContent=p.interests||"Не указаны";document.getElementById("profile-detail-contacts").textContent=p.showContacts?`${p.email} · ${p.phone}`:"Скрыты настройками приватности";const social=document.getElementById("profile-detail-social");social.textContent=p.showSocial?socialLabel(p.social):"Скрыта настройками приватности";social.href=p.showSocial&&p.social?p.social:"#";social.classList.toggle("disabled-link",!p.showSocial||!p.social);const header=document.getElementById("header-avatar");setAvatar(header,p);document.getElementById("side-user-name").textContent=p.name;document.getElementById("profile-stats").classList.toggle("role-hidden",!roleIs("volunteer"));document.getElementById("profile-extra").classList.toggle("role-hidden",!roleIs("volunteer"))}
function openProfileEditor(){const p=profiles[state.currentUser.role];modal("Редактировать профиль",`<div class="token-calculator profile-editor"><div class="avatar-editor"><div class="profile-photo" id="edit-avatar-preview">${p.avatar?"":p.initials}</div><label class="mini-btn upload-avatar">Загрузить фото<input id="avatar-file" type="file" accept="image/*"></label><button type="button" class="mini-btn" data-random-avatar>Инициалы</button></div><label>Имя / название<input id="edit-name" value="${p.name}"></label><label>Город<input id="edit-city" value="${p.city}"></label><label>Интересы / описание<input id="edit-interests" value="${p.interests}"></label><label>Email<input id="edit-email" type="email" value="${p.email}"></label><label>Телефон<input id="edit-phone" value="${p.phone}"></label><label>Ссылка на социальную сеть<input id="edit-social" type="url" placeholder="https://instagram.com/username" value="${p.social}"></label><div class="privacy-box"><b>Настройки публичного профиля</b><label><input id="edit-show-contacts" type="checkbox" ${p.showContacts?"checked":""}> Показывать контакты другим участникам</label><label><input id="edit-show-social" type="checkbox" ${p.showSocial?"checked":""}> Показывать ссылку на социальную сеть</label></div><button class="primary wide" data-save-profile>Сохранить изменения</button></div>`,"○");const preview=document.getElementById("edit-avatar-preview");if(p.avatar){preview.style.backgroundImage=`url(${p.avatar})`;preview.dataset.avatar=p.avatar}document.getElementById("avatar-file").addEventListener("change",e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{preview.textContent="";preview.style.backgroundImage=`url(${reader.result})`;preview.dataset.avatar=reader.result};reader.readAsDataURL(file)})}
function openPublicProfile(p){modal(p.name,`<div class="public-profile"><div class="person-avatar large-avatar">${p.initials}</div><span class="status-badge approved">Участник сообщества</span><p>${p.city} · ${p.interests}</p><div class="public-stats"><div><b>${p.hours}</b><small>часов</small></div><div><b>${p.events}</b><small>мероприятий</small></div></div><div class="public-info"><span><b>Контакты</b>${p.showContacts?p.email:"Скрыты пользователем"}</span><span><b>Социальная сеть</b>${p.showSocial&&p.social?`<a href="${p.social}" target="_blank" rel="noopener">${socialLabel(p.social)}</a>`:"Скрыта пользователем"}</span></div></div>`,"○")}

document.addEventListener("click",e=>{
  const notification=e.target.closest("[data-notification]");if(notification&&state.currentUser){const item=notifications[state.currentUser.role].find(n=>n.id===+notification.dataset.notification);if(item){item.read=true;renderNotifications();closeNotifications();go(item.page)}}
  const page=e.target.closest("[data-page]");if(page)go(page.dataset.page);
  const viewEvent=e.target.closest("[data-view-event]");if(viewEvent){const ev=events.find(x=>x.id===+viewEvent.dataset.viewEvent);modal(ev.title,`${ev.text}<br><br><b>Награда участнику: ${ev.reward} E</b><br>Режим просмотра: ${state.currentUser.label}. Запись и QR check-in доступны только участникам.`,"◇")}
  const viewReward=e.target.closest("[data-view-reward]");if(viewReward){const r=rewards.find(x=>x.id===+viewReward.dataset.viewReward);modal(r.title,`${r.text}<br><br><b>Стоимость: ${r.price} E</b><br>Покупка доступна только участникам. ${roleIs("partner")?"Для управления собственными предложениями используйте кабинет партнера.":""}`,"✦")}
  const join=e.target.closest("[data-join]");if(join&&requireRole("volunteer")){const id=+join.dataset.join;if(!volunteerData.joined.has(id)){volunteerData.joined.add(id);const ev=organizationData.events.find(x=>x.id===id);if(ev&&!ev.participants.some(x=>x.name===users.volunteer.name))ev.participants.push({name:users.volunteer.name,initials:"АИ",status:"Зарегистрирован",time:"—"});renderEvents();renderOrganization();modal("Вы записаны!","Организация увидит вашу регистрацию. В день события станет доступен QR check-in.","◇")}}
  const mission=e.target.closest("[data-mission]");if(mission&&requireRole("volunteer")){const id=+mission.dataset.mission,m=missions.find(x=>x.id===id);if(!volunteerData.missionStatus.has(id)){volunteerData.missionStatus.set(id,"Ожидает проверки");request({type:"mission",label:"Миссия",title:m.title,author:users.volunteer.name,detail:`${m.method} · награда ${m.reward} E`,missionId:id,amount:m.reward});volunteerData.transactions.unshift({title:m.title,rule:"Отправлено администратору",amount:m.reward,status:"Ожидает",date:"Только что"});renderMissions();renderTransactions();modal("Отправлено на проверку","Начисление произойдет только после решения администратора.","◷")}}
  const reward=e.target.closest("[data-reward]");if(reward&&requireRole("volunteer")){const r=rewards.find(x=>x.id===+reward.dataset.reward);if(volunteerData.balance<r.price)return modal("Недостаточно токенов",`Не хватает ${fmt(r.price-volunteerData.balance)} E`,"!");if(volunteerData.redeemed.has(r.id))return;volunteerData.redeemed.add(r.id);if(r.approval){addTransaction(r.title,"Токены зарезервированы до решения администратора",-r.price,"Зарезервировано");request({type:"large_reward",label:"Крупная награда",title:r.title,author:users.volunteer.name,detail:`Резерв ${r.price} E`,rewardId:r.id,amount:r.price});modal("Заявка создана","Администратор рассмотрит заявку. Токены зарезервированы.","✦")}else{addTransaction(r.title,"Покупка награды партнера",-r.price,"Списано");if(r.id===3){partnerData.redemptions.push({id:Date.now(),user:users.volunteer.name,initials:"АИ",reward:r.title,code:"EUR-NEW1",status:"Ожидает выдачи"});addNotification("partner","Награда ожидает выдачи",`${users.volunteer.name} зарезервировала «${r.title}».`,"partner","✦","yellow")}renderPartner();modal("Награда твоя!","Промокод: <b>EUR-NEW1</b>","✦")}renderRewards()}
  const friend=e.target.closest("[data-friend]");if(friend&&requireRole("volunteer")){volunteerData.friends.add(+friend.dataset.friend);renderPeople();toast("Заявка в друзья отправлена")}
  const viewPerson=e.target.closest("[data-view-person]");if(viewPerson&&requireRole("volunteer"))openPublicProfile(people.find(x=>x.id===+viewPerson.dataset.viewPerson));
  const sendEvent=e.target.closest("[data-send-event]");if(sendEvent&&requireRole("organization")){const ev=organizationData.events.find(x=>x.id===+sendEvent.dataset.sendEvent);ev.status="На модерации";request({type:"event",label:"Мероприятие",title:ev.title,author:users.organization.name,detail:"Требуется назначить награду",eventId:ev.id,amount:150});renderOrganization();toast("Мероприятие отправлено администратору")}
  const confirm=e.target.closest("[data-confirm-person]");if(confirm&&requireRole("organization")){const p=organizationData.events[0].participants[+confirm.dataset.confirmPerson];p.status="Подтверждено";if(p.name===users.volunteer.name){addTransaction(organizationData.events[0].title,"Участие подтверждено организацией",organizationData.events[0].reward);addNotification("volunteer","Участие подтверждено",`Начислено ${organizationData.events[0].reward} E за «${organizationData.events[0].title}».`,"wallet","✓","green")}audit("Подтверждено участие",`${p.name} · ${organizationData.events[0].title}`);renderOrganization();toast("Участие подтверждено, токены начислены системой")}
  const issue=e.target.closest("[data-issue]");if(issue&&requireRole("partner")){const r=partnerData.redemptions.find(x=>x.id==issue.dataset.issue);partnerData.redemptions=partnerData.redemptions.filter(x=>x.id!=issue.dataset.issue);audit("Подтверждена выдача награды",`${r.reward} · ${r.user}`);if(r.user===users.volunteer.name)addNotification("volunteer","Награда выдана",`Партнер подтвердил выдачу «${r.reward}».`,"rewards","✦","yellow");renderPartner();toast("Выдача подтверждена")}
  const moderate=e.target.closest("[data-moderate]");if(moderate&&requireRole("admin")){const id=+moderate.dataset.moderate,approved=moderate.dataset.decision==="approve",r=adminData.requests.find(x=>x.id===id);if(r.type==="mission"){volunteerData.missionStatus.set(r.missionId,approved?"Выполнено":"Отклонено");if(approved)addTransaction(r.title,"Проверено администратором",r.amount);addNotification("volunteer",approved?"Миссия одобрена":"Миссия отклонена",approved?`Начислено ${r.amount} E за «${r.title}».`:`Проверьте подтверждение миссии «${r.title}».`,"missions",approved?"✓":"!",approved?"green":"red");renderMissions()}if(r.type==="event"){const ev=organizationData.events.find(x=>x.id===r.eventId);if(ev){ev.status=approved?"Опубликовано":"Отклонено";if(approved)ev.reward=+document.querySelector(`[data-reward-input="${id}"]`).value;addNotification("organization",approved?"Мероприятие опубликовано":"Мероприятие отклонено",approved?`Для «${ev.title}» назначена награда ${ev.reward} E.`:`Проверьте данные мероприятия «${ev.title}».`,"organization",approved?"✓":"!",approved?"green":"red");renderOrganization()}}if(r.type==="partner_reward"){const reward=partnerData.rewards.find(x=>x.id===r.partnerRewardId);if(reward){reward.status=approved?"Активна":"Отклонена";addNotification("partner",approved?"Награда опубликована":"Награда отклонена",`«${reward.title}» · ${reward.status}.`,"partner",approved?"✓":"!",approved?"green":"red");renderPartner()}}if(!approved&&r.type==="large_reward")addTransaction(r.title,"Заявка отклонена, резерв возвращен",r.amount,"Возвращено");audit(approved?"Заявка одобрена":"Заявка отклонена",`${r.label}: ${r.title} · автор ${r.author}`);adminData.requests=adminData.requests.filter(x=>x.id!==id);renderAdmin();toast(approved?"Заявка одобрена":"Заявка отклонена")}
  const adminTab=e.target.closest("[data-admin-tab]");if(adminTab&&requireRole("admin")){document.querySelectorAll("[data-admin-tab]").forEach(x=>x.classList.remove("active"));adminTab.classList.add("active");renderAdmin(adminTab.dataset.adminTab)}
  const action=e.target.closest("[data-action]")?.dataset.action;
  if(action==="close")document.getElementById("modal").classList.remove("show");
  if(action==="close-notifications")closeNotifications();
  if(action==="read-all"&&state.currentUser){notifications[state.currentUser.role].forEach(n=>n.read=true);renderNotifications();toast("Все уведомления прочитаны")}
  if(action==="logout")logout();
  if(action==="checkin"&&requireRole("volunteer")){if(volunteerData.checkedIn.has(1))return toast("Повторный check-in заблокирован");volunteerData.checkedIn.add(1);const p=organizationData.events[0].participants.find(x=>x.name===users.volunteer.name);if(p){p.status="QR check-in";p.time="сейчас"}addNotification("organization","Новый QR check-in",`${users.volunteer.name} ожидает подтверждения участия.`,"organization","◎","green");renderOrganization();modal("Check-in зафиксирован","Теперь организация должна подтвердить ваше участие. До этого токены не начисляются.","◇")}
  if(action==="profile-task"&&requireRole("volunteer")){if(volunteerData.profileSocialAdded)return;volunteerData.profileSocialAdded=true;addTransaction("Добавлена социальная ссылка","Одноразовое правило профиля",5);e.target.closest(".profile-task").remove();toast("+5 E")}
  if(action==="calculator"&&requireRole("volunteer"))openCalculator();
  if(action==="create-event"&&requireRole("organization"))openEventForm();
  if(action==="org-profile"&&requireRole("organization"))modal("Профиль организации","<b>Фонд «Чистый город»</b><br>Алматы · Верифицирована<br>contact@clean-city.org · +7 727 000 00 00<br><br>Организация создает мероприятия и подтверждает участие, но не имеет личного кошелька.","▣");
  if(action==="confirm-all"&&requireRole("organization"))toast("Массовое подтверждение отключено: проверьте каждого участника");
  if(action==="create-reward"&&requireRole("partner"))openPartnerRewardForm();
  const editPartner=e.target.closest("[data-edit-partner-reward]");if(editPartner&&requireRole("partner"))openPartnerRewardForm(partnerData.rewards.find(x=>x.id===+editPartner.dataset.editPartnerReward));
  const submitEvent=e.target.closest("[data-submit-event]");if(submitEvent&&requireRole("organization")){organizationData.events.push({id:Date.now(),title:document.getElementById("new-event-title").value,status:"Черновик",reward:null,participants:[]});document.getElementById("modal").classList.remove("show");renderOrganization();toast("Черновик создан. Отправьте его на модерацию")}
  const savePartner=e.target.closest("[data-save-partner-reward]");if(savePartner&&requireRole("partner")){const existing=partnerData.rewards.find(x=>x.id===+savePartner.dataset.savePartnerReward),id=existing?.id||Date.now(),title=document.getElementById("partner-reward-title").value,price=+document.getElementById("partner-reward-price").value,quantity=+document.getElementById("partner-reward-quantity").value;if(existing)Object.assign(existing,{title,price,quantity,status:"На модерации"});else partnerData.rewards.push({id,title,price,quantity,status:"На модерации",issued:0});request({type:"partner_reward",label:"Награда партнера",title,author:users.partner.name,detail:`Стоимость ${price} E · количество ${quantity}`,partnerRewardId:id});document.getElementById("modal").classList.remove("show");renderPartner();toast("Награда отправлена на модерацию")}
  if(action==="new-rule"&&requireRole("admin"))openRuleForm();
  const submitRule=e.target.closest("[data-submit-rule]");if(submitRule&&requireRole("admin")){rules.push({title:document.getElementById("new-rule-title").value,amount:`+${document.getElementById("new-rule-amount").value} E`,detail:document.getElementById("new-rule-detail").value});audit("Создано правило токенов",rules.at(-1).title);document.getElementById("modal").classList.remove("show");renderAdmin("rules");toast("Правило добавлено")}
  if(e.target.closest("[data-block-user]")&&requireRole("admin"))toast("Доступ пользователя ограничен, решение записано в журнал");
  if(e.target.closest("[data-resolve-complaint]")&&requireRole("admin"))toast("Жалоба открыта для рассмотрения");
  if(action==="copy"&&requireRole("volunteer"))toast("Персональная ссылка скопирована");
  if(action==="edit"&&requireRole("volunteer","organization","partner","admin"))openProfileEditor();
  const randomAvatar=e.target.closest("[data-random-avatar]");if(randomAvatar){const preview=document.getElementById("edit-avatar-preview"),variants=["ЕВ","ДО","ВМ","ST"];preview.textContent=variants[Math.floor(Math.random()*variants.length)];preview.style.backgroundImage="";delete preview.dataset.avatar}
  const saveProfile=e.target.closest("[data-save-profile]");if(saveProfile&&requireRole("volunteer","organization","partner","admin")){const p=profiles[state.currentUser.role],preview=document.getElementById("edit-avatar-preview"),social=document.getElementById("edit-social");if(social.value&&!/^https?:\/\//i.test(social.value)){social.setCustomValidity("Введите полную ссылку, начинающуюся с https://");social.reportValidity();return}Object.assign(p,{name:document.getElementById("edit-name").value,city:document.getElementById("edit-city").value,interests:document.getElementById("edit-interests").value,email:document.getElementById("edit-email").value,phone:document.getElementById("edit-phone").value,social:social.value,showContacts:document.getElementById("edit-show-contacts").checked,showSocial:document.getElementById("edit-show-social").checked,initials:preview.textContent||p.initials,avatar:preview.dataset.avatar||null});state.currentUser.name=p.name;state.currentUser.short=p.name;state.currentUser.initials=p.initials;renderProfile();document.getElementById("modal").classList.remove("show");toast("Профиль сохранен и обновлен")}
});
document.getElementById("notification-button").addEventListener("click",openNotifications);
document.getElementById("notification-overlay").addEventListener("click",closeNotifications);
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeNotifications();document.getElementById("modal").classList.remove("show")}});
document.getElementById("chat-form").addEventListener("submit",e=>{e.preventDefault();if(!requireRole("volunteer"))return;const input=document.getElementById("chat-text");if(!input.value.trim())return;document.getElementById("messages").insertAdjacentHTML("beforeend",`<div class="message mine">${input.value}<small>сейчас · отправлено</small></div>`);input.value=""});
document.querySelectorAll("[data-auth-tab]").forEach(tab=>tab.addEventListener("click",()=>switchAuth(tab.dataset.authTab)));
document.querySelectorAll("[data-demo-user]").forEach(b=>b.addEventListener("click",()=>{b.classList.add("selected");setTimeout(()=>applyRole(users[b.dataset.demoUser]),180)}));
document.getElementById("login-form").addEventListener("submit",e=>{e.preventDefault();const email=document.getElementById("login-email").value.trim().toLowerCase(),password=document.getElementById("login-password").value,user=Object.values(users).find(x=>x.email===email&&x.password===password);if(!user){document.getElementById("login-error").textContent="Неверная почта или пароль";e.currentTarget.classList.remove("shake");requestAnimationFrame(()=>e.currentTarget.classList.add("shake"));return}applyRole(user)});
document.getElementById("register-form").addEventListener("submit",e=>{e.preventDefault();const name=document.getElementById("register-name").value.trim(),city=document.getElementById("register-city").value.trim(),role=document.getElementById("register-role").value,email=document.getElementById("register-email").value.trim().toLowerCase(),password=document.getElementById("register-password").value;const roleMeta={volunteer:{label:"Участник",start:"home",type:"Социальный профиль участника"},organization:{label:"Организация",start:"organization",type:"Профиль организации"},partner:{label:"Партнер",start:"partner",type:"Профиль партнера"}}[role];const initials=name.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"ЕВ";const user={email,password,role,name,short:name.split(/\s+/)[0],initials,label:roleMeta.label,start:roleMeta.start};profiles[role]={...profiles[role],name,city,email,initials,type:roleMeta.type};users[`registered-${Date.now()}`]=user;if(role!=="volunteer")addNotification(role,"Профиль создан",`Данные профиля «${name}» сохранены. Демо-доступ открыт для презентации.`,roleMeta.start,"✓","green");e.currentTarget.classList.add("register-success");e.submitter.disabled=true;e.submitter.querySelector("span").textContent="Профиль создан";e.submitter.querySelector("b").textContent="✓";setTimeout(()=>applyRole(user),520)});
document.querySelectorAll(".chip:not([data-admin-tab])").forEach(c=>c.addEventListener("click",()=>{c.parentElement.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));c.classList.add("active")}));
document.querySelector(".page-kicker").textContent=new Intl.DateTimeFormat("ru-RU",{weekday:"long",day:"numeric",month:"long"}).format(new Date()).replace(/^./,x=>x.toUpperCase());
renderEvents();renderMissions();renderRewards();renderTransactions();renderPeople();renderOrganization();renderPartner();renderAdmin();updateBalance();
